version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      kubernetes:
        patterns:
          - k8s.io/*
      observability:
        patterns:
          - github.com/prometheus/*
      cli:
        patterns:
          - github.com/spf13/*

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
