{{- if and (eq .Values.storage.driver "clickhouse") (not .Values.storage.clickhouse.existingSecret) .Values.storage.clickhouse.dsn }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-insight.fullname" . }}-clickhouse
  labels:
    {{- include "kube-insight.labels" . | nindent 4 }}
type: Opaque
stringData:
  dsn: {{ .Values.storage.clickhouse.dsn | quote }}
{{- end }}
